services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: spbe-cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    environment:
      - CLOUDFLARED_TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    depends_on:
      frontend:
        condition: service_started
    restart: always
    networks:
      - spbe-network
